apiVersion: kaas.mirantis.com/v1alpha1
kind: HostOSConfigurationModules
metadata:
  name: mcc-modules
spec:
  modules:
    - name: multipath
      version: 1.0.0
      sha256sum: 3efcd9e459806664e4ee0e0f5bd7eb360ca370ba89bcf3fd4700c6e4afe5421c
      url: https://github.com/reddydodda/mcc-modules/raw/main/files/multipath-1.0.0.tgz
