apiVersion: kaas.mirantis.com/v1alpha1
kind: HostOSConfigurationModules
metadata:
  name: mcc-modules
spec:
  modules:
    - name: multipath
      version: 1.0.0
      sha256sum: 0012112afdb9c1d221968982d514f85c8cda037d506f77788bd510177b2fd016
      url: https://github.com/reddydodda/mcc-modules/raw/main/files/multipath-1.0.0.tar.gz
