apiVersion: kaas.mirantis.com/v1alpha1
kind: HostOSConfigurationModules
metadata:
  name: mcc-modules
spec:
  modules:
    - name: multipath
      version: 1.0.0
      sha256sum: d651cd2d8dd697a3c5457aa7b4cbb8df50b8e780c18eefa838874522f232c4eb
      url: https://github.com/reddydodda/mcc-modules/raw/main/files/multipath-1.0.0.tar.gz
