apiVersion: kaas.mirantis.com/v1alpha1
kind: HostOSConfigurationModules
metadata:
  name: mcc-ps-modules
spec:
  modules:
    - name: multipath
      version: 1.0.0
      sha256sum: 9782b31ef451b9ef8ac4ea0507551e262d99f8cb4761e64bb9365bb9d2337bed
      url: https://github.com/reddydodda/mcc-modules/raw/main/files/multipath-1.0.0.tgz
