---
- name: Configure Multipath
  hosts: all
  become: true
  tasks:
    - name: Install multipath tools
      package:
        name: "{{ item }}"
        state: present
      loop:
        - multipath-tools-boot
        - multipath-tools
      when: values.install_multipath | default(true)

    - name: Configure multipath.conf
      template:
        src: multipath.conf.j2
        dest: /etc/multipath.conf
        owner: root
        group: root
        mode: '0644'
      notify: Restart multipath

    - name: Configure iSCSI
      import_tasks: iscsi_config.yaml
      when: iscsi_enabled | bool

  handlers:
    - name: Restart multipath
      systemd:
        name: multipathd
        state: restarted
